import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { PluginEntry, PluginFeatures } from './shared'
import { pluginDisplayName } from './shared'

type SkillSummary = {
  id: string
  name: string
  description?: string
}

const MAX_LISTED_SKILLS = 25

export async function writeCodexProviderPointer(pluginDir: string, plugin: PluginEntry, features: PluginFeatures) {
  await fs.mkdir(pluginDir, { recursive: true })
  const skills = await collectSkillSummaries(pluginDir, plugin)
  await fs.writeFile(path.join(pluginDir, 'AGENTS.md'), `${buildCodexAgentsPointer(plugin, skills, features)}\n`, 'utf-8')
}

export async function writeClaudeProviderPointer(pluginDir: string, plugin: PluginEntry, features: PluginFeatures) {
  await fs.mkdir(pluginDir, { recursive: true })
  const skills = await collectSkillSummaries(pluginDir, plugin)
  await fs.writeFile(path.join(pluginDir, 'CLAUDE.md'), `${buildClaudePointer(plugin, skills, features)}\n`, 'utf-8')
}

export async function writeCursorProviderFiles(pluginDir: string, plugin: PluginEntry, features: PluginFeatures) {
  await fs.mkdir(pluginDir, { recursive: true })
  const summaries = await collectSkillSummaries(pluginDir, plugin)
  await fs.writeFile(path.join(pluginDir, 'CURSOR.md'), `${buildCursorInstallNotes(plugin, summaries, features)}\n`, 'utf-8')
  const rulesDir = path.join(pluginDir, 'rules')
  await fs.mkdir(rulesDir, { recursive: true })
  await fs.writeFile(path.join(rulesDir, 'agentrig-provider.mdc'), `${buildCursorProjectRule(plugin, summaries, features)}\n`, 'utf-8')
}

function buildCodexAgentsPointer(plugin: PluginEntry, skills: SkillSummary[], features: PluginFeatures) {
  return [
    `# ${pluginDisplayName(plugin.manifest)} AgentRig Pointer`,
    '',
    'Generated by AgentRig for Codex. Do not edit this file as canonical source.',
    '',
    '## Source Of Truth',
    '- Canonical plugin metadata lives upstream in the AgentRig `plugin.json`.',
    '- Canonical skill instructions live in AgentRig `skills/*/SKILL.md` files.',
    '- Provider manifests, MCP config, and this pointer are generated outputs.',
    '',
    '## Repo Expectations',
    '- Keep provider files generated from AgentRig plugin sources.',
    '- Prefer small provider notes that point to canonical skill docs.',
    '- Run `agentrig doctor --provider codex <registry/plugin>` after install or export changes.',
    '',
    '## AgentRig Skills',
    'Codex loads skill names and descriptions before reading full `SKILL.md` bodies. Trigger on these summaries, then open the matching skill file when needed.',
    ...formatSkillBullets(skills),
    '',
    '## Routing',
    '- Use `project-spec-packager` for app, SaaS, API, AI product, or internal-tool ideas that need a build-ready spec package.',
    '- Run `ship-gate` before merge, release, or handoff when tests, security, packaging, and final verification matter.',
    '- Run `agentrig doctor --provider codex <registry/plugin>` to verify plugin, capability, MCP, env, and generated-file health.',
    '',
    '## MCP And Approvals',
    features.hasClaudeMcp
      ? '- MCP config is exported as `.mcp.json` and referenced from `.codex-plugin/plugin.json`.'
      : '- No MCP config is exported for this plugin.',
    '- Review local MCP commands and required env vars before enabling.',
    '- Keep sandbox and approval settings conservative for untrusted repos; approve write, network, and shell actions deliberately.',
  ].join('\n')
}

function buildClaudePointer(plugin: PluginEntry, skills: SkillSummary[], features: PluginFeatures) {
  return [
    `# ${pluginDisplayName(plugin.manifest)} Claude Code Pointer`,
    '',
    'Generated by AgentRig for Claude Code. Do not edit this file as canonical source.',
    '',
    '## Source Of Truth',
    '- Canonical plugin metadata lives upstream in the AgentRig `plugin.json`.',
    '- Canonical skill instructions live in AgentRig `skills/*/SKILL.md` files.',
    '- Provider manifests, MCP config, settings, and this pointer are generated outputs.',
    '',
    '## AgentRig Skills',
    'Claude Code should use the installed plugin skills from `skills/` and read the full `SKILL.md` only when a trigger matches.',
    ...formatSkillBullets(skills),
    '',
    '## MCP',
    features.hasClaudeMcp
      ? '- MCP config is exported as `.mcp.json`; check `/mcp` after install to confirm servers are visible.'
      : '- This plugin does not export MCP servers.',
    '- Claude plugin MCP paths may use `${CLAUDE_PLUGIN_ROOT}`, `${CLAUDE_PLUGIN_DATA}`, and `${CLAUDE_PROJECT_DIR}`.',
    '- Run `agentrig doctor --provider claude-code <registry/plugin>` to verify env vars and provider visibility.',
    '',
    '## Settings And Reload',
    features.hasSettings
      ? '- Review exported `settings.json` and confirm the intended Claude Code scope before enabling.'
      : '- No plugin `settings.json` is exported; keep provider settings in the Claude Code scope you install to.',
    '- Reload Claude Code after plugin or MCP changes so `/mcp`, skills, commands, hooks, and settings refresh.',
  ].join('\n')
}

function buildCursorInstallNotes(plugin: PluginEntry, skills: SkillSummary[], features: PluginFeatures) {
  return [
    `# ${pluginDisplayName(plugin.manifest)} Cursor Install Notes`,
    '',
    'Generated by AgentRig for Cursor. Do not edit this file as canonical source.',
    '',
    '## Source Of Truth',
    '- Canonical plugin metadata lives upstream in the AgentRig `plugin.json`.',
    '- Canonical skill instructions live in AgentRig `skills/*/SKILL.md` files.',
    '- Cursor rules, MCP config, and these install notes are generated outputs.',
    '',
    '## Cursor Use',
    '- Use the generated project rule in `rules/agentrig-provider.mdc` for provider-neutral routing.',
    features.hasClaudeMcp
      ? '- MCP config is exported as `mcp.json`; configure or enable it through Cursor MCP settings as appropriate.'
      : '- This plugin does not export MCP servers.',
    '- Run `agentrig doctor --provider cursor <registry/plugin>` to verify generated files before relying on the install.',
    '',
    '## AgentRig Skills',
    ...formatSkillBullets(skills),
  ].join('\n')
}

function buildCursorProjectRule(plugin: PluginEntry, skills: SkillSummary[], features: PluginFeatures) {
  return [
    '---',
    `description: AgentRig provider-neutral guidance for ${plugin.manifest.name}`,
    'alwaysApply: false',
    '---',
    '',
    `# ${pluginDisplayName(plugin.manifest)} AgentRig Rule`,
    '',
    'Use this AgentRig plugin through provider-neutral prompts and canonical skill docs.',
    '',
    'Source of truth:',
    '- AgentRig `plugin.json` for upstream plugin metadata and capability declarations.',
    '- AgentRig `skills/*/SKILL.md` for canonical instructions.',
    '- Generated Cursor files are outputs, not canonical policy.',
    '',
    'When working:',
    '- Trigger on the short skill descriptions below, then read the matching `SKILL.md`.',
    '- Use `project-spec-packager` for build-ready app or product specification packages.',
    '- Run `ship-gate` before release, merge, or final handoff when applicable.',
    '- Run `agentrig doctor --provider cursor <registry/plugin>` after install/export changes.',
    features.hasClaudeMcp
      ? '- If MCP is needed, use the generated `mcp.json` through Cursor MCP configuration.'
      : '- No MCP config is exported for this plugin.',
    '',
    'Skills:',
    ...formatSkillBullets(skills),
  ].join('\n')
}

async function collectSkillSummaries(pluginDir: string, plugin: PluginEntry): Promise<SkillSummary[]> {
  const skillsRoot = path.join(pluginDir, 'skills')
  const summaries: SkillSummary[] = []
  try {
    const entries = await fs.readdir(skillsRoot, { withFileTypes: true })
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      const skillPath = path.join(skillsRoot, entry.name, 'SKILL.md')
      const text = await fs.readFile(skillPath, 'utf-8').catch(() => '')
      const frontmatter = parseFrontmatter(text)
      summaries.push({
        id: entry.name,
        name: frontmatter.name ?? entry.name,
        ...(frontmatter.description ? { description: shorten(frontmatter.description, 150) } : {}),
      })
    }
  } catch {
    // Skills are optional for provider bundles.
  }

  const declared = declaredSkillIds(summaries, plugin)
  return declared.sort((left, right) => left.id.localeCompare(right.id))
}

function declaredSkillIds(existing: SkillSummary[], plugin: PluginEntry) {
  return [...new Map(existing.map((entry) => [entry.id, entry])).values()]
}

function parseFrontmatter(text: string): { name?: string; description?: string } {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!match) return {}
  const values: { name?: string; description?: string } = {}
  for (const line of match[1]!.split(/\r?\n/)) {
    const field = line.match(/^(name|description):\s*(.*)$/)
    if (!field) continue
    const value = field[2]!.trim().replace(/^['"]|['"]$/g, '')
    if (field[1] === 'name') values.name = value
    if (field[1] === 'description') values.description = value
  }
  return values
}

function formatSkillBullets(skills: SkillSummary[]) {
  if (!skills.length) return ['- No skills directory was exported for this plugin.']
  const visible = skills.slice(0, MAX_LISTED_SKILLS)
  const lines = visible.map((skill) => {
    const description = skill.description ?? skill.name
    return `- \`${skill.id}\`: ${description}`
  })
  if (skills.length > visible.length) {
    lines.push(`- ${skills.length - visible.length} more skills are available in \`skills/\`.`)
  }
  return lines
}

function shorten(value: string, maxLength: number) {
  const normalized = value.replace(/\s+/g, ' ').trim()
  if (normalized.length <= maxLength) return normalized
  return `${normalized.slice(0, maxLength - 1).trimEnd()}...`
}
