name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true

      - name: Install
        run: vp install --frozen-lockfile
      - name: Build registry
        run: vp run repo:registry:build

      - name: Typecheck CLI
        run: vp run repo:typecheck:cli

      - name: Build CLI
        run: vp run repo:build:cli

      - name: Build docs
        run: vp run repo:docs:build
