name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: voidzero-dev/setup-vp@45e5c098f1095cc6b65fd92534603e7be70386c1
        with:
          node-version: 24
          cache: true

      - name: Install
        run: vp install --frozen-lockfile

      - name: Check
        run: vp run repo:check

      - name: Typecheck CLI
        run: vp run repo:typecheck:cli

      - name: Build CLI
        run: vp run repo:build:cli

      - name: Build docs
        run: vp run repo:docs:build
