name: Vite+ Playground Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: voidzero-dev/setup-vp@45e5c098f1095cc6b65fd92534603e7be70386c1
        with:
          node-version: 24
          cache: true
      - run: vp install --frozen-lockfile
      - run: vp run repo:playground:vite-plus:check
